export const GET_IS_LOADING_TO_STATE = "GET_IS_LOADING_TO_STATE";
export const GET_SEARCH_VALUE_TO_STATE = "GET_SEARCH_VALUE_TO_STATE";
export const GET_MACHINES_FROM_API = "GET_MACHINES_FROM_API";
export const GET_MACHINE_TYPES_FROM_API = "GET_MACHINE_TYPES_FROM_API";
export const GET_TRADE_POINTS_FROM_API = "GET_TRADE_POINTS_FROM_API";
